In [1]:
# =====================================
# 1. Setup
# =====================================

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [2]:
# =====================================
# 2. Imports
# =====================================

import pandas as pd

from src.data_loader import load_performance
from src.target_generation import (
    create_loan_level_performance,
    create_bssi
)

In [3]:
# =====================================
# 3. Load Data
# =====================================

perf_df = load_performance(
    "../data/raw/historical_data_time_2018Q1.txt"
)

perf_df.shape

(13873084, 32)

In [4]:
# =====================================
# 4. Create Loan-Level Performance
# =====================================

loan_perf = create_loan_level_performance(
    perf_df
)

loan_perf.head()

  loan_identifier  max_delinquency  ever_ra  ever_modified  ever_assistance
0    F18Q10000001                0    False          False            False
1    F18Q10000002                1    False          False            False
2    F18Q10000003                0    False          False            False
3    F18Q10000004                0    False          False            False
4    F18Q10000005                0    False          False            False

In [5]:
# =====================================
# 5. Create BSSI
# =====================================

loan_perf = create_bssi(
    loan_perf
)

loan_perf.head()

,loan_identifier,max_delinquency,ever_ra,ever_modified,ever_assistance,bssi
0,F18Q10000001,0,False,False,False,0
1,F18Q10000002,1,False,False,False,1
2,F18Q10000003,0,False,False,False,0
3,F18Q10000004,0,False,False,False,0
4,F18Q10000005,0,False,False,False,0

In [6]:
# =====================================
# 6. Analyze Target
# =====================================

loan_perf["bssi"].value_counts()

bssi
0    254031
1     32249
2     10371
3       165
Name: count, dtype: int64

In [7]:
loan_perf["bssi"].value_counts(
    normalize=True
) * 100

bssi
0    85.585346
1    10.864980
2     3.494084
3     0.055590
Name: proportion, dtype: float64

In [8]:
# =====================================
# 7. Analyze Stress Events
# =====================================

loan_perf[
    [
        "ever_ra",
        "ever_modified",
        "ever_assistance"
    ]
].sum()

ever_ra              165
ever_modified       3000
ever_assistance    21071
dtype: int64

In [9]:
loan_perf["stress_flag"] = (
    loan_perf["bssi"] > 0
).astype(int)

In [10]:
loan_perf.to_parquet(
    "../data/processed/loan_perf_2018Q1.parquet",
    index=False
)

In [11]:
loan_perf.shape

(296816, 7)