In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("Project Root:", PROJECT_ROOT)

Project Root: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac

In [4]:
import pandas as pd
train_df = pd.read_parquet(
    "../data/modeling/train_baseline.parquet"
)

train_df.columns.tolist()

['credit_score',
 'first_payment_date',
 'first_time_homebuyer_indicator',
 'maturity_date',
 'msa',
 'mortgage_insurance_pct',
 'num_units',
 'occupancy_status',
 'cltv',
 'dti',
 'original_upb',
 'ltv',
 'interest_rate',
 'channel',
 'prepayment_penalty_indicator',
 'amortization_type',
 'property_state',
 'property_type',
 'loan_identifier',
 'loan_purpose',
 'original_loan_term',
 'num_borrowers',
 'seller_name',
 'super_conforming_flag',
 'harp_indicator',
 'property_valuation_method',
 'interest_only_indicator',
 'mortgage_insurance_type',
 'vantagescore_4',
 'bssi',
 'stress_flag',
 'year',
 'quarter',
 'quarter_num']

In [5]:
train_df.dtypes

credit_score                      float64
first_payment_date                  int64
first_time_homebuyer_indicator        str
maturity_date                       int64
msa                               float64
mortgage_insurance_pct              int64
num_units                           int64
occupancy_status                      str
cltv                              float64
dti                               float64
original_upb                        int64
ltv                               float64
interest_rate                     float64
channel                               str
prepayment_penalty_indicator          str
amortization_type                     str
property_state                        str
property_type                         str
loan_identifier                       str
loan_purpose                          str
original_loan_term                  int64
num_borrowers                       int64
seller_name                           str
super_conforming_flag                 str
harp_indicator                        str
property_valuation_method             str
interest_only_indicator             int64
mortgage_insurance_type               str
vantagescore_4                        str
bssi                                int64
stress_flag                         int64
year                                int64
quarter                               str
quarter_num                         int64
dtype: object

In [6]:
train_df[
    [
        "first_payment_date",
        "maturity_date"
    ]
].head()

   first_payment_date  maturity_date
0              201803         204802
1              201804         203803
2              201804         203803
3              201805         204804
4              201803         204802

In [7]:
train_df["vantagescore_4"].value_counts(
    dropna=False
).head(20)

vantagescore_4
7    449033
N    183580
Y     28705
Name: count, dtype: int64

In [8]:
train_df["interest_only_indicator"].value_counts(
    dropna=False
)

interest_only_indicator
7    643329
1     17989
Name: count, dtype: int64

In [9]:
train_df[
    [
        "interest_only_indicator",
        "mortgage_insurance_type",
        "vantagescore_4"
    ]
].head(20)

    interest_only_indicator mortgage_insurance_type vantagescore_4
0                         7                       N              7
1                         7                       N              7
2                         7                       N              7
3                         7                       N              7
4                         7                       N              7
5                         7                       N              7
6                         7                       N              7
7                         7                       N              7
8                         7                       N              7
9                         7                       N              7
10                        7                       N              7
11                        7                       N              7
12                        7                       N              7
13                        7                       N              N
14                        7                       N              7
15                        7                       N              N
16                        7                       N              7
17                        7                       N              7
18                        7                       N              7
19                        7                       N              7