In [26]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("Project Roaot:", PROJECT_ROOT)

Project Roaot: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac

In [51]:
import importlib

import scripts.build_target_dataset
import scripts.pipeline
import scripts.build_feature_store
import scripts.build_master_dataset
import scripts.combine_quarters
import src.feature_engineering
import scripts.build_modeling_datasets

importlib.reload(scripts.build_target_dataset)
importlib.reload(scripts.build_feature_store)
importlib.reload(scripts.pipeline)
importlib.reload(scripts.build_master_dataset)
importlib.reload(src.feature_engineering)
importlib.reload(scripts.combine_quarters)
importlib.reload(scripts.build_modeling_datasets)

IndentationError: unindent does not match any outer indentation level (pipeline.py, line 229)

In [23]:
import scripts.build_target_dataset as btd

dir(btd)

['Path',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'build_target_dataset',
 'create_bssi',
 'create_loan_level_performance',
 'create_stress_flag',
 'create_stress_level',
 'load_origination',
 'load_performance',
 'validate_loan_counts']

In [4]:
from src.schema import ORIGINATION_COLUMNS

In [5]:
ORIGINATION_COLUMNS

['credit_score',
 'first_payment_date',
 'first_time_homebuyer_indicator',
 'maturity_date',
 'msa',
 'mortgage_insurance_pct',
 'num_units',
 'occupancy_status',
 'cltv',
 'dti',
 'original_upb',
 'ltv',
 'interest_rate',
 'channel',
 'prepayment_penalty_indicator',
 'amortization_type',
 'property_state',
 'property_type',
 'postal_code',
 'loan_identifier',
 'loan_purpose',
 'original_loan_term',
 'num_borrowers',
 'seller_name',
 'servicer_name',
 'super_conforming_flag',
 'pre_harp_loan_sequence_number',
 'program_indicator',
 'harp_indicator',
 'property_valuation_method',
 'interest_only_indicator',
 'mortgage_insurance_cancellation_indicator']

In [24]:
from scripts.pipeline import run_pipeline

run_pipeline(
    quarter="all"
)

Processing 2018Q1
Loading data...
Running validation...
Origination Loans : 296816
Performance Loans : 296816
Validation Passed
Creating loan-level dataset...
Saving parquet...
   bssi  stress_flag  stress_level
0     0            0             0
1     1            1             1
2     0            0             0
3     0            0             0
4     0            0             0
stress_level
0    254031
1     32249
2     10536
Name: count, dtype: int64
Done
============================================================
BUILDING MASTER DATASET
============================================================

Loading origination data...
Origination shape: (296816, 32)

Loading target dataset...
Target shape: (296816, 8)

Loading performance features...
Performance Features shape: (296816, 18)

Cleaning origination data...

Merging datasets...
After target merge: (296816, 36)
After performance merge: (296816, 50)
Master shape after merge: (296816, 50)

Creating Borrower Serviceability Score...

Validating dataset...
Master dataset validation passed.

Saving dataset...

Dataset saved successfully.
Final shape: (296816, 65)

Quarter processing complete.

Processing 2018Q2
Loading data...
Running validation...
Origination Loans : 364502
Performance Loans : 364502
Validation Passed
Creating loan-level dataset...
Saving parquet...
   bssi  stress_flag  stress_level
0     0            0             0
1     0            0             0
2     0            0             0
3     0            0             0
4     0            0             0
stress_level
0    314896
1     36957
2     12649
Name: count, dtype: int64
Done
============================================================
BUILDING MASTER DATASET
============================================================

Loading origination data...
Origination shape: (364502, 32)

Loading target dataset...
Target shape: (364502, 8)

Loading performance features...
Performance Features shape: (364502, 18)

Cleaning origination data...

Merging datasets...
After target merge: (364502, 36)
After performance merge: (364502, 50)
Master shape after merge: (364502, 50)

Creating Borrower Serviceability Score...

Validating dataset...
Master dataset validation passed.

Saving dataset...

Dataset saved successfully.
Final shape: (364502, 65)

Quarter processing complete.

Processing 2018Q3
Loading data...
Running validation...
Origination Loans : 336669
Performance Loans : 336669
Validation Passed
Creating loan-level dataset...
Saving parquet...
   bssi  stress_flag  stress_level
0     0            0             0
1     0            0             0
2     0            0             0
3     0            0             0
4     2            1             2
stress_level
0    290416
1     34197
2     12056
Name: count, dtype: int64
Done
============================================================
BUILDING MASTER DATASET
============================================================

Loading origination data...
Origination shape: (336669, 32)

Loading target dataset...
Target shape: (336669, 8)

Loading performance features...
Performance Features shape: (336669, 18)

Cleaning origination data...

Merging datasets...
After target merge: (336669, 36)
After performance merge: (336669, 50)
Master shape after merge: (336669, 50)

Creating Borrower Serviceability Score...

Validating dataset...
Master dataset validation passed.

Saving dataset...

Dataset saved successfully.
Final shape: (336669, 65)

Quarter processing complete.

Processing 2018Q4
Loading data...
Running validation...
Origination Loans : 287447
Performance Loans : 287447
Validation Passed
Creating loan-level dataset...
Saving parquet...
   bssi  stress_flag  stress_level
0     0            0             0
1     0            0             0
2     1            1             1
3     0            0             0
4     1            1             1
stress_level
0    248948
1     28478
2     10021
Name: count, dtype: int64
Done
============================================================
BUILDING MASTER DATASET
============================================================

Loading origination data...
Origination shape: (287447, 32)

Loading target dataset...
Target shape: (287447, 8)

Loading performance features...
Performance Features shape: (287447, 18)

Cleaning origination data...

Merging datasets...
After target merge: (287447, 36)
After performance merge: (287447, 50)
Master shape after merge: (287447, 50)

Creating Borrower Serviceability Score...

Validating dataset...
Master dataset validation passed.

Saving dataset...

Dataset saved successfully.
Final shape: (287447, 65)

Quarter processing complete.

NameError: name 'stages_to_run' is not defined

In [13]:
import pandas as pd
master_df = pd.read_parquet(
    "../data/processed/master_dataset_2018Q1.parquet"
)

print(master_df.columns.tolist())

['credit_score', 'first_payment_date', 'first_time_homebuyer_indicator', 'maturity_date', 'msa', 'mortgage_insurance_pct', 'num_units', 'occupancy_status', 'cltv', 'dti', 'original_upb', 'ltv', 'interest_rate', 'channel', 'prepayment_penalty_indicator', 'amortization_type', 'property_state', 'property_type', 'postal_code', 'loan_identifier', 'loan_purpose', 'original_loan_term', 'num_borrowers', 'seller_name', 'servicer_name', 'program_indicator', 'property_valuation_method', 'interest_only_indicator', 'mortgage_insurance_cancellation_indicator', 'ever_ra', 'bssi', 'stress_flag', 'stress_level', 'max_delinquency', 'avg_delinquency', 'months_delinquent', 'loan_age_max', 'loan_age_avg', 'remaining_term_avg', 'current_rate_avg', 'current_rate_max', 'current_rate_min', 'estimated_ltv_avg', 'estimated_ltv_max', 'ever_modified', 'modification_count', 'ever_assistance', 'assistance_count', 'ever_zero_balance', 'rate_volatility', 'credit_score_norm', 'dti_norm', 'interest_rate_norm', 'ltv_norm', 'num_borrowers_norm', 'bss', 'bss_bucket', 'bss_level', 'delinquency_intensity', 'modification_intensity', 'assistance_intensity', 'eltv_drift', 'quarter', 'year', 'quarter_num']

In [54]:
import importlib

import scripts.pipeline

importlib.reload(
    scripts.pipeline
)

from scripts.pipeline import run_pipeline

In [55]:
from inspect import signature

print(
    signature(run_pipeline)
)

(stage, quarter=None, version='v1', description='')

In [45]:
run_pipeline(stage="combine")

Found:
master_dataset_2018Q1.parquet
master_dataset_2018Q2.parquet
master_dataset_2018Q3.parquet
master_dataset_2018Q4.parquet
Loading master_dataset_2018Q1.parquet
Loading master_dataset_2018Q2.parquet
Loading master_dataset_2018Q3.parquet
Loading master_dataset_2018Q4.parquet
Combined Shape: (1285434, 65)
Saved: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/processed/master_dataset_2018.parquet

Combined dataset created.

In [ ]:
run_pipeline(stage="combine")

In [48]:
from scripts.pipeline import run_pipeline

run_pipeline(
    stage="feature_store",
    version="v1",
    description="Initial dissertation feature store"
)

============================================================
BUILDING FEATURE STORE
============================================================
Input Shape: (1285434, 65)
Serviceability score calculated.
Saved: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/feature_store/v1/stress_prediction/feature_store.parquet
Shape: (1285434, 48)
Saved: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/feature_store/v1/stress_severity/feature_store.parquet
Shape: (1285434, 60)
Saved: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/feature_store/v1/serviceability/feature_store.parquet
Shape: (1285434, 60)
Saved: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/feature_store/v1/explainability/feature_store.parquet
Shape: (1285434, 65)

Feature Store Version Created: v1

In [50]:
import pandas as pd

df = pd.read_parquet(
    "../data/feature_store/v1/stress_prediction/feature_store.parquet"
)

print(
    df["quarter"]
    .value_counts()
)

quarter
2018Q2    364502
2018Q3    336669
2018Q1    296816
2018Q4    287447
Name: count, dtype: int64

In [56]:
run_pipeline(
    stage="modeling",
    version="v1"
)

============================================================
BUILDING MODELING DATASETS
============================================================

Processing stress_prediction

Saved datasets to /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/feature_store/v1/stress_prediction
Train: (661318, 48)
Valid: (336669, 48)
Test : (287447, 48)

Processing stress_severity

Saved datasets to /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/feature_store/v1/stress_severity
Train: (661318, 60)
Valid: (336669, 60)
Test : (287447, 60)

Processing serviceability

Saved datasets to /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac/data/feature_store/v1/serviceability
Train: (661318, 60)
Valid: (336669, 60)
Test : (287447, 60)

Modeling datasets created.

In [14]:
missing = (
    master_df
    .isna()
    .mean()
    .sort_values(
        ascending=False
    )
)

print(
    missing.head(30)
)

msa                       0.095723
bss_level                 0.017853
bss                       0.017853
bss_bucket                0.017853
dti_norm                  0.017715
dti                       0.017715
credit_score              0.000094
credit_score_norm         0.000094
cltv                      0.000057
ltv_norm                  0.000047
ltv                       0.000047
eltv_drift                0.000047
ever_assistance           0.000000
current_rate_min          0.000000
current_rate_max          0.000000
current_rate_avg          0.000000
estimated_ltv_avg         0.000000
estimated_ltv_max         0.000000
remaining_term_avg        0.000000
loan_age_avg              0.000000
ever_modified             0.000000
modification_count        0.000000
interest_rate_norm        0.000000
assistance_count          0.000000
ever_zero_balance         0.000000
rate_volatility           0.000000
months_delinquent         0.000000
num_borrowers_norm        0.000000
delinquency_intensity     0.000000
modification_intensity    0.000000
dtype: float64

In [15]:
print(
    master_df["bssi"]
    .value_counts()
)

print(
    master_df["stress_flag"]
    .value_counts(
        normalize=True
    )
)

print(
    master_df["stress_level"]
    .value_counts(
        normalize=True
    )
)

bssi
0    254031
1     32249
2     10371
3       165
Name: count, dtype: int64
stress_flag
0    0.855853
1    0.144147
Name: proportion, dtype: float64
stress_level
0    0.855853
1    0.108650
2    0.035497
Name: proportion, dtype: float64

In [16]:
perf_cols = [

    "max_delinquency",
    "avg_delinquency",
    "months_delinquent",

    "loan_age_max",
    "loan_age_avg",

    "current_rate_avg",

    "estimated_ltv_avg",

    "modification_count",

    "assistance_count"

]

master_df[
    perf_cols
].describe()

,max_delinquency,avg_delinquency,months_delinquent,loan_age_max,loan_age_avg,current_rate_avg,estimated_ltv_avg,modification_count,assistance_count
count,296816.000000,296816.000000,296816.000000,296816.000000,296816.000000,296816.000000,296816.000000,296816.000000,296816.000000
mean,0.626917,0.084283,1.127847,45.765764,23.006426,4.384471,176.581646,0.336424,0.624734
std,2.753317,0.597197,5.018904,27.858000,13.956206,0.450832,221.259208,3.804917,2.885886
min,0.000000,0.000000,0.000000,0.000000,0.000000,2.500000,1.911111,0.000000,0.000000
25%,0.000000,0.000000,0.000000,25.000000,13.000000,4.125000,71.891304,0.000000,0.000000
50%,0.000000,0.000000,0.000000,35.000000,18.000000,4.375000,105.433333,0.000000,0.000000
75%,0.000000,0.000000,0.000000,77.000000,38.500000,4.625000,146.243534,0.000000,0.000000
max,72.000000,33.744444,88.000000,92.000000,57.500000,6.625000,999.000000,79.000000,51.000000

In [17]:
master_df[
    [
        "bss",
        "bss_bucket",
        "bss_level"
    ]
].head()

         bss bss_bucket  bss_level
0  49.500970     Medium        3.0
1  46.169609        Low        2.0
2  68.144792  Very High        5.0
3  47.764241        Low        2.0
4  73.865808  Very High        5.0

In [18]:
master_df[
    "bss_level"
].value_counts(
    normalize=True
)

bss_level
1.0    0.200005
5.0    0.200002
3.0    0.199999
4.0    0.199999
2.0    0.199995
Name: proportion, dtype: float64

In [19]:
master_df[
    [
        "credit_score",
        "dti",
        "ltv",
        "interest_rate"
    ]
].corr()

               credit_score       dti       ltv  interest_rate
credit_score       1.000000 -0.150596 -0.047917      -0.259214
dti               -0.150596  1.000000  0.082021       0.135274
ltv               -0.047917  0.082021  1.000000       0.169842
interest_rate     -0.259214  0.135274  0.169842       1.000000

In [20]:
master_df.groupby(
    "stress_flag"
)[
    [
        "credit_score",
        "dti",
        "ltv",
        "interest_rate"
    ]
].mean()

             credit_score        dti        ltv  interest_rate
stress_flag
0              749.532960  35.316185  74.434294       4.369545
1              722.361594  37.965220  75.560106       4.492719

In [ ]:
from scripts.pipeline import run_pipeline

QUARTERS = [
    "2018Q1",
    "2018Q2",
    "2018Q3",
    "2018Q4"
]

for quarter in QUARTERS:

    run_pipeline(
        quarter=quarter,
        force_rebuild=True
    )

In [ ]:
from scripts.build_combined_dataset import (
    build_combined_dataset
)

combined_df = build_combined_dataset(
    input_files=[
        "../data/processed/master_dataset_2018Q1.parquet",
        "../data/processed/master_dataset_2018Q2.parquet",
        "../data/processed/master_dataset_2018Q3.parquet",
        "../data/processed/master_dataset_2018Q4.parquet"
    ],
    output_path="../data/processed/master_dataset_2018.parquet"
)

In [ ]:
from scripts.build_feature_store import (
    build_feature_store
)

build_feature_store(
    input_path="../data/processed/master_dataset_2018.parquet",
    output_dir="../data/modeling"
)

In [ ]:
import pandas as pd

pd.read_parquet(
    "../data/modeling/train_baseline.parquet"
).shape

In [ ]:
import pandas as pd
pd.read_parquet(
    "../data/modeling/train_bss.parquet"
).shape

In [ ]:
for name in [
    "train_baseline",
    "valid_baseline",
    "test_baseline"
]:

    df = pd.read_parquet(
        f"../data/modeling/{name}.parquet"
    )

    print(
        name,
        df.shape
    )

In [ ]:
for name in [
    "train_baseline",
    "valid_baseline",
    "test_baseline"
]:

    df = pd.read_parquet(
        f"../data/modeling/{name}.parquet"
    )

    print(
        name,
        round(
            df["stress_flag"].mean() * 100,
            2
        )
    )

In [ ]:
train_df = pd.read_parquet(
    "../data/modeling/train_baseline.parquet"
)

print(train_df.shape)

train_df.columns.tolist()

In [ ]:
master_df = pd.read_parquet(
    "../data/processed/master_dataset_2018.parquet"
)

print(master_df.columns.tolist())

In [ ]:
q1 = pd.read_parquet(
    "../data/processed/master_dataset_2018Q1.parquet"
)

print(q1.columns.tolist())

In [ ]:
for col in [
    "seller_name",
    "servicer_name",
    "msa"
]:
    print(
        col,
        train_df[col].nunique()
    )

In [ ]:
loan_perf.columns.tolist()